### ISSUE TITLE
Is it possible to set the modal´s height always to 100% ?

### ISSUE THREAD

**Issue by digitalgenossen** [dixso/custombox#100]
Hi dixso,

I would like to open your modal and use it as an info bar sliding in from left. For the position I set the values 'left, top' - this already works fine and the effect of sliding in looks really good.  
Is it possible to set the height of the modal always to 100% (or better min-height:100% to keep the ability of scrolling if there is much content shown in the modal)? I tried different things but didn´t get it done. I hope you can help?

Thanks a lot in advance for answering my question :-)
Kai

**Comment by dixso** [comment]
Hi,
I'm sorry but now is not possible.
Regards.
