### ISSUE TITLE
is it possible to show content depending on input

### ISSUE THREAD

**Issue by sahilbrewari** [dixso/custombox#101]
Hi dixso,

I am trying to implement custombox on http://www.prashnavali.org/test/index.html, my immediate requirement is to show content inside the modal box which is fetched via a php script (from a mysql database).

Now the content is coming as a separate page depending on the number in the input field. How do I put this content inside the modal box.

Await your reply,

Thanks,
Sahil

**Comment by dixso** [comment]
Hi Sahil,
For example:
<pre>
document.getElementById('answermodal').addEventListener('click', function ( e ) {
    var value = document.getElementById("someInput").value;
    Custombox.open({
        target: 'answer.php?q=' + value,
	effect: 'fadein'
    });
    e.preventDefault();
});
</pre>

**Comment by sahilbrewari** [comment]
Hi disxo,

Perfect. Works just fine now. Got the website mobile friendly finally.

http://www.prashnavali.org/

Thanks,
Sahil
