### ISSUE TITLE
sometimes close action crashes

### ISSUE THREAD

**Issue by ipetkov88** [dixso/custombox#103]
Here is the code:
        $('#seatNumberHint').on('click', function (e) {
            Custombox.open({
                target: '#seatNumberHintText',
                effect: 'fadein',
                speed: 300,
            });
            e.preventDefault();
        });

this is happening on last version of chrome, on firefox it is working fine.

If clicked on the overlay after the box is already appeared everything is fine.
But, If I am clicking very fast while opening the popup box it freeze on closing (maybe) and I am blocked on gray background and cannot do anything.

**Comment by dixso** [comment]
Hi,
I need to investigate.

**Comment by ipetkov88** [comment]
even with automatically close it crashes and frozen and cannot proceed...
http://clip2net.com/s/3cijnD2 - before click on ('?') to popup a msg
http://clip2net.com/s/3cijEqa - working...
http://clip2net.com/s/3cij9NT - but sometimes it crashes

**Comment by ipetkov88** [comment]
actually, no matter the speed of clicking its happening sometimes....

**Comment by dixso** [comment]
Sorry but I don't understand...

**Comment by ipetkov88** [comment]
in the first post I told that this bug appears only if I click very fast while the popup box appearing and I am trying to close it immediately, but later on I realized that its happening something even if I click normally and i am trying to close it after it is already show, but it freeze too...

**Comment by dixso** [comment]
Hi,
Can check if it works?

**Comment by ipetkov88** [comment]
I think now it works, didn't crash since a month. Not sure whether browser updated during this time.
