### ISSUE TITLE
Unable to validate controls on modal popup using jquery validate plugin 

### ISSUE THREAD

**Issue by nsgawli** [dixso/custombox#105]
When I am trying to validate controls on modal popup using jquery validate plugin..it doesnt work.. When modal popup comes out.it removes html code for content on modal popup automatically. So validate() method couldnt find controls on the page it was already removed by combobox.js..

**Comment by dixso** [comment]
Hi,
You could put your code in jsfiddle.net?

**Comment by nsgawli** [comment]
http://jsfiddle.net/nsgawli/9tgcw9cu/

**Comment by dixso** [comment]
Hi,
Please, use the new version.
And the script has to be like this:
<pre>
$(document).on('click', '.submit', function ( e ) {
    var $form = $(this).closest('form');
    $form.validate();
    $form.valid();
    e.preventDefault();
});
</pre>
