### ISSUE TITLE
Go to top, again.

### ISSUE THREAD

**Issue by psrafo** [dixso/custombox#106]
Hello, you have this(https://github.com/dixso/custombox/issues/9) old bug again, but now only on new updated effects.
When i click on new updated effects (Letmein, Makeway, Slip) in http://dixso.github.io/custombox/.

**Comment by dixso** [comment]
Hi,
I don't remember exactly.
You can make a video (again)?
Thanks!

**Comment by psrafo** [comment]
Please, http://x11.zoom.am/out.ogv

When i open dialog with this effects (Letmein, Makeway, Slip), page scroll's to top, and then, when i close dialog, goes back to normal position.

**Comment by dixso** [comment]
Yeah, It is as it should be...

**Comment by psrafo** [comment]
Ou!

I think it is bug, and my team too. But it's your way, thanks.

**Comment by dixso** [comment]
The PR's are welcome :)

**Comment by psrafo** [comment]
"PR" ? What you mean ?

**Comment by dixso** [comment]
PR -> Pull requests

**Comment by psrafo** [comment]
A! Thanks.
