### ISSUE TITLE
Modal overflow question

### ISSUE THREAD

**Issue by usb248** [dixso/custombox#107]
Hi,

 In CSS file of your plugin i see for div `.custombox-modal-wrapper`, this value for overflow property : `overflow-y: scroll;`. Why always show a scrollbar even when we don't need.? Why not rather `overflow-y: auto;` ? Someone can justify this choice ?

**Comment by dixso** [comment]
Hi,
Sorry, it's a small error.
In MAC the scrollbar is always hidden...
In the next version I will change.
Regards.

**Comment by ddimitrioglo** [comment]
Hi!
Scroll always shown, but page content moves to right when modal window appears.
I hope you will fix it.
Thanks!

**Comment by usb248** [comment]
Yes, i confirm...

**Comment by jtfl2008** [comment]
@ddimitrioglo css file like this

/* .custombox-open,
.custombox-open body {
    overflow: hidden;
} */
.custombox-modal-container {
    margin: 0 auto;
    position: relative;
    height: 100%;
    overflow: hidden;
}

**Comment by usb248** [comment]
Hi, are you sure to add "overflow hidden" on .custombox-modal-container will not prevent to scroll the content if overflow vertically ?

**Comment by dixso** [comment]
Hi,
I'm working on the next version (https://github.com/dixso/custombox/commit/b748b48402f949736d3b99e7dd80174f8af19753).
Regards.

**Comment by usb248** [comment]
When is the next release ?

**Comment by ddimitrioglo** [comment]
@dixso your changes still didn't help

**Comment by dixso** [comment]
Can you check in this JS?
https://raw.githubusercontent.com/dixso/custombox/develop/dist/custombox.min.js

**Comment by usb248** [comment]
Any issue, any release ?

**Comment by dixso** [comment]
Is solved?
https://www.dropbox.com/s/6dpyvhbv8d5uhfh/ie10.mov?dl=0

**Comment by usb248** [comment]
For me it's ok, when you merge develop branche ?

**Comment by dixso** [comment]
New release:
https://github.com/dixso/custombox/releases/tag/2.2.6

Thanks!

**Comment by ddimitrioglo** [comment]
Hi,
New release didn't help me, the main page is still mooving to the right on showing the modal popup...

**Comment by dixso** [comment]
What browser and what OS?

**Comment by ddimitrioglo** [comment]
Windows - Chrome and Firefox
You can try it on www.h2h.md ("Войти" menu item)

**Comment by zuhloobie** [comment]
I'm seeing the same as ddimitrioglo - Windows 64bit, Chrome Version 43.0.2357.130 m.

**Comment by dixso** [comment]
Ok, thanks.

**Comment by dixso** [comment]
Hi all,
Fixed in the new release (coming soon).

**Comment by AlbinGasi** [comment]
Also, if you think that you will have more content in popup modal, you can change this:

```
.custombox-content>* {
  max-height: unset !important; /* instead of 95% */
}
.custombox-content {
  display: block !important; /* instead of flex */
}
```

and your content should not be cut out.
