### ISSUE TITLE
Not Working With WordPress

### ISSUE THREAD

**Issue by technofreaky** [dixso/custombox#108]
I am currently developing an WordPress Plugin. for that i tried to use it in admin page but the total script doesn't respond.

**Comment by dixso** [comment]
Need more info...

**Comment by technofreaky** [comment]
hi
i used this script in my wordpress plugin. when i click a button a modal should come but the total content is appended to a body not coming as modal ?

**Comment by dixso** [comment]
I don't understand, sorry.
The script has an error?

**Comment by technofreaky** [comment]
No script error but the ajax data is appending to body with out style

On Sun, Jul 05, 2015 at 2:02 pm, Julio de la Calle < notifications@github.com [notifications@github.com] > wrote:
I don't understand, sorry.
The script has an error?

—
Reply to this email directly or view it on GitHub
[https://github.com/dixso/custombox/issues/108#issuecomment-118595278] .[https://github.com/notifications/beacon/ABzAf4FbXhww-l1k3DNBpk9fuMrYGZOrks5oaOMfgaJpZM4DhY9Y.gif]

**Comment by dixso** [comment]
Could you put a demo on the jsfiddle.net?

**Comment by technofreaky** [comment]
i used in WordPress [http://wordpress.org]
will try to send screenshot soon :)

On Sun, Jul 5, 2015 at 2:10 PM, Julio de la Calle <notifications@github.com>
wrote:

> Could you put a demo on the jsfiddle.net?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dixso/custombox/issues/108#issuecomment-118595483>.
>



-- 

Varun Sridharan
Cell : +91 904 224 8903
Email : varunsridharan23@gmail.com
Website : http://www.varunsridharan.in/
