### ISSUE TITLE
scroll modal content on touch

### ISSUE THREAD

**Issue by hundstage** [dixso/custombox#109]
Hi,

i use the custombox for displaying content that is higher than the viewport, so users need to scroll. works fine on desktop devices as a scrollbar is shown to scroll the modal content.
but on touch devices it's not possible to scroll the box content.

do you have an idea how to fix this?

thanks, christoph

**Comment by dixso** [comment]
Hi,
In my iOS 8 works fine.
I need more details for testing.
Regards.
