### ISSUE TITLE
Error when calling "built" method

### ISSUE THREAD

**Issue by uncledrella** [dixso/custombox#110]
Hello

I'm having some problems when Custombox.open is called. In a few cases (only 4 or 5 people out of thousands) an error occurs: `Uncaught TypeError: Cannot read property 'getPropertyValue' of null`

I don't know if it happens in _utilities.zIndex() or in the zIndex overflow part in the _private.built() method. We are using a minified version of the plugin and that's all the feedback we could get.

Any clue??

Thanks!

**Comment by dixso** [comment]
Hi,
You have added the legacy.js file before custombox.js?
Regards ;-)
