### ISSUE TITLE
not making images  responsive.

### ISSUE THREAD

**Issue by pioneersingh321** [dixso/custombox#111]
i have use custombox for images ... it working very fine but one issue i found that is " its not making image responsive in custombox ... plz solve the issue as soon as possible

**Comment by LinK316** [comment]
is easy for resolve, add .trim() in the swith in line 594
![screenshot 2015-02-27 11 55 17](https://cloud.githubusercontent.com/assets/1808053/6418053/8893d4ac-be77-11e4-92e9-f31b2edc0178.png)

**Comment by pioneersingh321** [comment]
thanks its working fine with chrome but its not working with Firefox ...

**Comment by pioneersingh321** [comment]
thanks its working fine with chrome but its not working with Firefox ...

**Comment by dixso** [comment]
Hi,
All images that are within the modal are responsive.
![captura de pantalla 2015-03-10 a las 7 02 51](https://cloud.githubusercontent.com/assets/1495899/6569990/9e11de3a-c6f3-11e4-86ae-404fdf60032b.png)
You could put your code in jsfiddle.net?
