### ISSUE TITLE
Modal does not display in iOS 6

### ISSUE THREAD

**Issue by Ezentyr** [dixso/custombox#113]
Hello. Your wonderful modal window has ticked almost all the boxes for my project. In device testing however, I have noticed that the modal windows do not display in iOS6 devices. Only the overlay is displayed.

I am using browserstack to test my solution on multiple devices, but you can also see the same issue on your demonstration page:

http://dixso.github.io/custombox/

If you access this on any iOS6 based device (usually iPhone 5 and below) the modal does not display. iOS7 devices (iPhone 5S and above) work perfectly.

I am including the legacy js file but this seems to have no effect.

iOS6 now has very small usage footprint, but it's still significant enough for me to hesitate.

If you could assist in any way with this problem it would be very much appreciated!

**Comment by dixso** [comment]
Hi,
I'm sorry but I will not give support for iOS 6, for me it is like the Internet Explorer 7.
Regards.
