### ISSUE TITLE
In case of multiple dialog when I click on the 'overlay-click' not close.

### ISSUE THREAD

**Issue by prepared91** [dixso/custombox#115]
Hi,
Dialog box does not respond to multiple overlay-click the event custombox.
1.: open: http://dixso.github.io/custombox/
2.: click - Open infinite modals: example.
3.: click - open other modal
4.: click next to moda (overlay-click).
The last modal is closes but the next modal not respon. (just close button)

Sorry for my bad english.

**Comment by AgelxNash** [comment]
+1

**Comment by dixso** [comment]
Hi,
What browser?
I just tested with Google Chrome (OS X) and it has worked.

**Comment by prepared91** [comment]
Google Chrome, IE 10+, Firefox (Windows ~ all browser)

**Comment by dixso** [comment]
I check it with virtualbox and it works.
https://www.dropbox.com/s/6dpyvhbv8d5uhfh/ie10.mov?dl=0

**Comment by prepared91** [comment]
Yes the button works.
Click here beside, (overlay, (dark-background), only closes the top box, and then does not respond to rest, next click.
open lot of modal-> and click overlay and click next overlay(background)

**Comment by spostad7** [comment]
+1

**Comment by dixso** [comment]
Hi,
Fixed in the new release (coming soon).
