### ISSUE TITLE
Is not working properly setting width.

### ISSUE THREAD

**Issue by PopovMaxim** [dixso/custombox#116]
Hello. My problem is that the width parameter does not work correctly.
For example, I set the width to 700, I open a modal window, and the width of the window is aligned with the internal components, unless explicitly set the width of the window through the stylesheet or attribute Style, then when you first open a modal window width is correct, but when you reopen again aligned to the internal components. What to do?

Js code:

Custombox.open({
		target: 		'#click_and_buy',
		cache: 			false,
		escKey: 		<?=$modal['escKey'];?>,
		overlayColor: 	'<?=$modal['overlayColor'];?>',
		overlayOpacity: <?=$modal['overlayOpacity'];?>,
		overlayClose: 	<?=$modal['overlayClose'];?>,
		overlaySpeed: 	<?=$modal['overlaySpeed'];?>,
		overlayEffect: 	'<?=$modal['overlayEffect'];?>',
                overlay: 		<?=$modal['overlay'];?>,
		width: 			<?=$modal['width'];?>,
		effect: 		'<?=$modal['effect'];?>',
		position: 		'<?=$modal['position'];?>',
		animation: 		'<?=$modal['animation'];?>',
		speed: 			<?=$modal['speed'];?>,
		complete: function() {
		       
		}
 });

Sorry for my bad english :)

first open
![2015-04-15_170514](https://cloud.githubusercontent.com/assets/11962759/7160426/fec1c43a-e399-11e4-9a03-71e30eda5a6f.png)

second open
![2015-04-15_170525](https://cloud.githubusercontent.com/assets/11962759/7160427/fec4e138-e399-11e4-8538-09b51a525d52.png)

**Comment by dixso** [comment]
Hi,
You could put your code in jsfiddle.net?
