### ISSUE TITLE
Doesn't work on Safari 5.1.7

### ISSUE THREAD

**Issue by STF-GR** [dixso/custombox#117]
Hi,
Great modal plugin. I've tested it across all browsers. On my Safari that runs on W7 it doesn't work.
I was extremely surprised that it worked perfect on IE7 even.
Maybe it has a small fix for Safari. Thank you.

Also I tried on an old Nexus S, same result.

**Comment by dixso** [comment]
Hi,
Sorry, but I do not give support for this version, is too old.
The current version of Safari is 8.0.5
Regards.
