### ISSUE TITLE
Object does not  support property getOwnPropertyDescriptor

### ISSUE THREAD

**Issue by Fareeha-Naz09** [dixso/custombox#118]
In lagecy.min.js file  shows Object does not  support property getOwnPropertyDescriptor error at page loading time. my project in html4 and jsf 1.2. Please help me for any work around.

Thanks

**Comment by dixso** [comment]
Hi,
Need more info.
- OS?
- Browser?
- Version?
Put your code in jsfiddle.net.

Regards.

**Comment by Fareeha-Naz09** [comment]
I am working at windows 7 64 bit and Internet Explorer 9.
Thanks for your response.

**Comment by dixso** [comment]
Hi,
I think it works:
https://www.dropbox.com/s/i80s3ucoxgm9kwe/custombox-ie9.mov?dl=0

Don't forget put your code in jsfiddle.net.
