### ISSUE TITLE
Responsive Width

### ISSUE THREAD

**Issue by dponinski** [dixso/custombox#119]
Is there anyway to make this responsive to screen size?

**Comment by dixso** [comment]
Full width 100%?

**Comment by dponinski** [comment]
Tried it. Doesn't work :(. I think it might be something in the plugin js. I don't know enough JavaScript to handle such a task but I thought I might bring it up here.

**Comment by zuhloobie** [comment]
@dponinski - this what you mean? http://jsfiddle.net/zuhloobie/ex5dyp96/2/.

No edits to JS were made - just CSS.

**Comment by dixso** [comment]
Hi,
Fixed in the new release (coming soon).
https://github.com/dixso/custombox/commit/e7d9e9ae7235bddd2f169cfba834642b9936fe58
