### ISSUE TITLE
How can i include a js file on complete custombox

### ISSUE THREAD

**Issue by Srinucnu** [dixso/custombox#120]
i want to load a js file in custombox on complete function.

**Comment by dixso** [comment]
First to all, hi? and then, please?
With jQuery:
<pre>
Custombox.open({
    target:     'demo/xhr/ajax.html',
    complete:   function () {
        $.getScript("your_script.js", function(){
            // Callbackj
        });
    }
});
</pre>

**Comment by Srinucnu** [comment]
Sorry typed it in a hurry, so forgot to use basic formalities. will try it out and let you know. Thank you.
