### ISSUE TITLE
Content Scale effect is not smooth enough

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [dixso/custombox#121]
On your website the home page in the right side in the effect list. The last effect is not previewed smoothely. Kindly fix that up

Thank You,
Utkarsh

**Comment by dixso** [comment]
Hi,
Could you give me more information?
- Platform
- Browser
- Version of the browser.

Regards.

**Comment by Utkarsh-vishnoi** [comment]
It's a windows PC. 64 bit running the latest version of google chrome.
Actually I dont know which version the google chrome is. I tried to search about it.but couldn't find the specific version but if i try to update it. It keep me saying that you have the latest version

**Comment by dixso** [comment]
Sorry, but I think it works correctly...
Could you record a video or screenshot?

**Comment by Utkarsh-vishnoi** [comment]
I have recorded the video but github doesn't  support .webm format.

**Comment by Utkarsh-vishnoi** [comment]
Where to upload them

**Comment by dixso** [comment]
I don't know, but maybe dropbox?
