### ISSUE TITLE
Main entry in bower.json

### ISSUE THREAD

**Issue by damianobarbati** [dixso/custombox#122]
Please add a "main" entry in your bower.json with the js and css needed to use the plugin.
Gulp and grunt use it to concat and minify automatically needed files.

**Comment by dixso** [comment]
Hi,
Thanks for your comment.
https://github.com/dixso/custombox/releases/tag/2.2.6

Regards!

**Comment by damianobarbati** [comment]
Big up! : )

2015-06-27 10:02 GMT+02:00 Julio de la Calle <notifications@github.com>:
