### ISSUE TITLE
Suggestion improvement

### ISSUE THREAD

**Issue by usb248** [dixso/custombox#127]
Hi, 

  Why not display a pretty CSS3 or pur Javascript loading animation in current modal during loading content when target is an url ?

**Comment by dixso** [comment]
Hi,
thanks for you suggestion.
For the new version :)

**Comment by dixso** [comment]
Hi,
Added in the new release (coming soon).
https://github.com/dixso/custombox/commit/4970c385916fd1ac3bdc4ffe3beaf33d27b48df5

**Comment by usb248** [comment]
Hi, cool ! I wait your release ;)
