### ISSUE TITLE
Different targets for different links

### ISSUE THREAD

**Issue by zuhloobie** [dixso/custombox#128]
Taking a look at your demo page, you have several links that target #modal. Each #modal has the exact same text no matter what example link you click on. How would you go about coding it so that each link targets a different modal so that you can have different text for each? I don't really want to have super long code that basically repeats the code for firing the plugin but with a different target. If I had 200 links, that would mean repeating that firing code 200 times but with a different target for each. Unless that's the only way? Thanks...

**Comment by zuhloobie** [comment]
Fiddle: https://jsfiddle.net/zuhloobie/1d8yh701/

My desire is to have each box open a custombox modal that has text specific to that box.

If what I want is outside the scope of this plugin or is inefficient for this plugin...please let me know :)

**Comment by dixso** [comment]
Hi,
Multiple ways to do this:
https://jsfiddle.net/1d8yh701/1/

**Comment by zuhloobie** [comment]
I know you are super busy, so please know I really appreciate you taking the time to write down a few options for me. I was tinkering around with a "$(this).parent().find()" method and while it worked, I really like your options that are much cleaner. Thank you!!

**Comment by dixso** [comment]
Thank you for using this plugin.
