### ISSUE TITLE
Repeating Transparent Pattern for Overlay

### ISSUE THREAD

**Issue by zuhloobie** [dixso/custombox#130]
Is it possible to add a repeating background PNG pattern to lay on top of the overlay color that is declared? Similar to "background-image" + "background-color" for DIVs...

**Comment by dixso** [comment]
In the modal or in the overlay?

**Comment by zuhloobie** [comment]
Overlay

**Comment by dixso** [comment]
Put your custom styles here:
https://github.com/dixso/custombox/blob/master/src/css/custombox.css#L25

**Comment by zuhloobie** [comment]
Ah! Thanks!
