### ISSUE TITLE
When inside modal, click to next or previous modal

### ISSUE THREAD

**Issue by zuhloobie** [dixso/custombox#131]
Say I'm in a modal, is it possible to add next/prev buttons inside that modal that would close the current modal session and open either the next or previous modal?

I have a page of boxes that open their own modal and it'd be cool if one could next/prev through them if they wanted to. Rather than close and open.

**Comment by dixso** [comment]
Hi,
You can open multiple modals and close the specific modal.

**Comment by zuhloobie** [comment]
Yeah, I know you can stack modals - but I want the user experience to be better than that...to where they just press a next/previous button instead of opening and closing several modals. Possible?

**Comment by dixso** [comment]
Hi,
It is possible if you add yours code but I think not is a feature common.
