### ISSUE TITLE
infinite modals with push effect

### ISSUE THREAD

**Issue by zuhloobie** [dixso/custombox#141]
I click Modal 1's trigger and it pushes the body to the right and shows Modal 1. Inside Modal 1 I have another trigger for Modal 2 and when clicked it also enters from the left. This works fine until I click close on Modal 2 and the body behind Modal 1 slides to the left. 

Shouldn't the body stay put until you close the very last opened (Modal 1)?

See basic fiddle: http://jsfiddle.net/zuhloobie/wkry223n/

**Comment by dixso** [comment]
Hi,
Please, wait to the new version 3.0.0.
https://github.com/dixso/custombox/issues/115

**Comment by zuhloobie** [comment]
Okay :)
