### ISSUE TITLE
Uncaught TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by spostad7** [dixso/custombox#143]
tanx for v 3.0.0,
I get above error when I use the latest version. as result, the plugin does not work.
I have the following recall code:
```javascript
$('.get-course').on('click', function (e) {
    e.preventDefault;
    Custombox.open({
        target: this.getAttribute('href'),
        effect: 'fadein',
        loading: {
            parent: ['sk-folding-cube'],
            childrens: [
                ['sk-cube', 'sk-cube1'],
                ['sk-cube', 'sk-cube2'],
                ['sk-cube', 'sk-cube4'],
                ['sk-cube', 'sk-cube3']
            ]
        },
        open: function () {
            stud_selected();
        }
    });
});
```

**Comment by dixso** [comment]
Hi,
Add the script legacy.min.js before the custombox.min.js

**Comment by spostad7** [comment]
tanx! fixed! now it's working
but I still don't see any loading effect!
Is it possible to have some delay before modal show up to see loading effect?

**Comment by dixso** [comment]
Hi,
Sorry for delay, in the next release.

**Comment by dixso** [comment]
Added in develop: 021ee724781af746c2bde44d16a27fc282e23bde

**Comment by andilengubane** [comment]
Hi guys 
 am using IE 11.0.9600.18525 running the project built in mvc and am getting 0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'assign' 

obj = Object.assign({}, obj, {
                validTo: new Date(parseInt(obj.validTo.substr(6))),

            });

**Comment by dixso** [comment]
Hi,
Try the new version.
Regards!
