### ISSUE TITLE
With option width full

### ISSUE THREAD

**Issue by usb248** [dixso/custombox#144]
On FF (OS Win 10), i can't close the modal.
I can't scroll until the top of the modal...
Screenshot : 
![capture](https://cloud.githubusercontent.com/assets/7659927/9561849/5fade5d4-4e58-11e5-989d-8edff684e608.PNG)

**Comment by dixso** [comment]
Hi,
Could you put the code in jsfiddle.net?

**Comment by usb248** [comment]
Hi,

 No need. On your demo page, just click on the demo, resize your screen (the height), try to scroll on the top... TADA :).

**Comment by dixso** [comment]
Solved in develop: https://github.com/dixso/custombox/commit/762410d42db927be4cb59e10a025e88635135a63

**Comment by usb248** [comment]
Hi,

Cool thanks !
