### ISSUE TITLE
Uncaught TypeError: Cannot read property 'settings' of undefined

### ISSUE THREAD

**Issue by basherr** [dixso/custombox#145]
I try to chain multiple custom box? 
e.x click on next button open the next popup and so as previous open previous popup.
 
      $("#next_step2").on('click', function(event) {
               Custombox.close(); //closing old custom box
                event.preventDefault();
                    Custombox.open({
                        target: '#step2',
                        effect: 'fadein',
                        width : 600
                    });
                }); 
    $("#back_step1").on('click', function(event) { // throws error while going back
                Custombox.close(); // closing old custombox
                event.preventDefault();
                        Custombox.open({
                            target: '#step1',
                            effect: 'fadein',
                            width : 600
                        });
                });

**Comment by dixso** [comment]
Hi,
Could you put the code in jsfiddle.net?

**Comment by basherr** [comment]
https://jsfiddle.net/0mkLarjj/4/

**Comment by dixso** [comment]
Hi,
Solved in develop: d2ffdfd74955e81d6c563b009119529dd049f396
And in your fiddle: https://jsfiddle.net/0mkLarjj/6/
