### ISSUE TITLE
Can't open another custom box after I close one

### ISSUE THREAD

**Issue by jwknz** [dixso/custombox#150]
Is it correct that I need to refresh the page after I close a box before I can open another one?

**Comment by dixso** [comment]
Hi,
Shouldn't do it.
Can you put a example in jsfiddle?

**Comment by jwknz** [comment]
Not right now, because I am not In front my Mac, but it happens when I am nesting occurances. So when I initiate one and then have a button that triggers another one (like in your example) and then close one, I can't open another one.

The same happens when you use the multiple occurances example in your documentation.

Regards,

Jeff Kranenburg
Sent from iPhone




On Wed, Sep 23, 2015 at 10:40 PM -0700, "Julio de la Calle" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Shouldn't do it.
Can you put a example in jsfiddle?

-

**Comment by JustMikey** [comment]
Have you managed to reproduce it?
