### ISSUE TITLE
Box is transparent (no white background)

### ISSUE THREAD

**Issue by pihug12** [dixso/custombox#151]
![test](https://cloud.githubusercontent.com/assets/678038/10178810/62556e02-6702-11e5-9102-33ffc40d6074.gif)

x Custombox 3.0.1
x Firefox 41 & IE 11

The CSS "custombox.min.css" is included in the page, but there is no background in the box.

	for(i = 0; i < elements.length; i++) {
		//elements[i].attr("href", "raphael/get_info_groupe.php?jour=" + param_date + "&centre=" + param_centre + "&groupe=" + nom);
		elements[i].attr({cursor: 'pointer'});
		elements[i][0].addEventListener('click', function( e ) {
            Custombox.open({
                target: "raphael/get_info_groupe.php?jour=" + param_date + "&centre=" + param_centre + "&groupe=" + nom,
                effect: 'fadein'
            });
            e.preventDefault();
        });
	}

**Comment by dixso** [comment]
Put a background color in your "div".

**Comment by pihug12** [comment]
I'm now sure which div you're talking about. The PHP I call returns only `<table> ... </table>`.
I thought I would have a nice white box like the demo if I included `<link rel="stylesheet" href="custombox.min.css">`.
Maybe I miss something? Should I add a "special" `div` to put the content in a box?

**Comment by dixso** [comment]
Yes, the difference between other plugins is that custombox is fully customizable.
