### ISSUE TITLE
"legacy.min.js" seems needed for IE11?

### ISSUE THREAD

**Issue by pihug12** [dixso/custombox#152]
The script "legacy.min.js" seems needed for Internet Explorer 11. Do you consider IE11 as legacy?

**JavaScript console IE11:**
![capture1](https://cloud.githubusercontent.com/assets/678038/10179084/fa328d76-6703-11e5-9b47-b861ece87375.png)

**Debugger IE11:**
![capture2](https://cloud.githubusercontent.com/assets/678038/10179085/fa3b30a2-6703-11e5-9fdc-9e8d6012be53.png)

**Comment by dixso** [comment]
Hi,
I think not.
Why?

**Comment by tero** [comment]
IE11 and Windows Phone 8.1 both doesn't work without legacy.js. Getting same Object doesn't have assign property or method.
