### ISSUE TITLE
"index.html" demo doesn't work

### ISSUE THREAD

**Issue by pihug12** [dixso/custombox#153]
**Full page (taken with Firefox 41) :** https://imgur.com/No5bHVj

The style of the webpage seems missing.

jQuery seems needed:
![capture3](https://cloud.githubusercontent.com/assets/678038/10179238/f7acf5ea-6704-11e5-9347-d6003198dc48.png)

**Comment by dixso** [comment]
Put these files in your apache public directory.

**Comment by pihug12** [comment]
OK It works from a web server. It's not very handy.

These links doesn't seem to work from local:
```html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="//google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
```

**Comment by dixso** [comment]
Please, include "http:" before "//"

**Comment by pihug12** [comment]
Much better! The page is fine now, thanks. :-)
