### ISSUE TITLE
CSS3 animations are triggered when the overlay is displayed or removed

### ISSUE THREAD

**Issue by druellan** [dixso/custombox#154]
Hi!
I'm not sure if this one is Custombox's fault or something related to the way CSS3 animations are handled by the browsers: when Custombox displays or hides the overlay, some CSS3 animations previously  displayed are triggered again.

I have a JSFiddle here: http://jsfiddle.net/9y4jgkm0/9/

Tested it on Chrome 45.0.2454.101 and Firefox 41.0.1

I'm still checking this, but perhaps you guys already got the answer.
Thanks!

**Comment by druellan** [comment]
Interesting.
If you set overlay: false, the modal box is not displayed, but some animations are triggered.

**Comment by druellan** [comment]
Ok, seems that the problem is related to the `appendChild`method.
Starting on line 133 there is a `while`
```
this.main = document.createElement('div');
while ( document.body.firstChild ) {
  this.main.appendChild(document.body.firstChild);
}
document.body.appendChild(this.main);
```
If I understand this snippet correctly: it is reattaching the entire DOM into the "main" element? This for sure is going to trigger all kind of events, specially animations and transitions.

**Comment by dixso** [comment]
Hi,
Yes, custombox need a wrapper div for the animations.
But you can add a class in your other animation with javascript and use autobuild of the custombox.
http://jsfiddle.net/9y4jgkm0/10/

**Comment by druellan** [comment]
Hi dixso!
Thanks for the explanation, is not exactly a solution for us, but is a good tip to point us to the right direction.
BTW, you can't `overlay:false` and show the dialog, right? If there is no overlay, there is no object for the dialog to appendto. Is that correct?
