### ISSUE TITLE
Open on document ready

### ISSUE THREAD

**Issue by digitalgenossen** [dixso/custombox#156]
Hi dixso,

I tried to open my modal automatically on document ready this way, but it does not work:

<script type="text/javascript">
    $(document).ready(function() {
        $("#modal").trigger('click');
    });
</script> 

Can you help?

Thank you & kind regards,
Kai

**Comment by digitalgenossen** [comment]
![unbenannt-2](https://cloud.githubusercontent.com/assets/6715837/10726113/f60c7f40-7bd0-11e5-9138-6e3ce166008f.jpg)

**Comment by dixso** [comment]
Duplicate https://github.com/dixso/custombox/issues/96
