### ISSUE TITLE
Not opens in native android browser

### ISSUE THREAD

**Issue by indiwine** [dixso/custombox#158]
I have tested in native Android browser on different android versions (4-5) - modal window not opens.
But it works in Google Chrome for android.

**Comment by dixso** [comment]
Hi,
Could you give me more info about the effect name?
Regards.

**Comment by tero** [comment]
Having this same issue with effetc fadein.

**Comment by indiwine** [comment]
Yes. Sorry for late reply.
I used fadein and blur effects

**Comment by dixso** [comment]
Hi,
Could you try in develop branch:
https://github.com/dixso/custombox/commit/cff838f141143c74e74507b4d1e82ceaf6a790f0
