### ISSUE TITLE
No modal at all with effect "content scale", "push", "door", ...

### ISSUE THREAD

**Issue by LeoFlandin** [dixso/custombox#161]
Tested on http://dixso.github.io/custombox/ Google Chrome Version 46.0.2490.86 m Windows 7.

No modal at all on : "content scale", "push", "door", "scale", "slide together", "corner, "slip", "slit".
Slow and bad animation on others.

**Comment by dixso** [comment]
Solved in develop:
https://github.com/dixso/custombox/commit/0dc312a53725e09db2f72e43ad108fd2f52bf753

**Comment by LeoFlandin** [comment]
You rock man !
I think the slow animation are due to a regression in the current Chrome version.
Thanks a lot.
