### ISSUE TITLE
Safari 5.1.7 on Windows freezes web page without showing modal

### ISSUE THREAD

**Issue by jure123** [dixso/custombox#162]
I tested LEGACY.js on Safari 5.1.7 (build 7534.57.2). It only shows background overlay, but not modal is shown and user cannot exit (thus it appears like the web page is frozen).

**Comment by dixso** [comment]
Hi,
Which effect?

**Comment by jure123** [comment]
All effects (I tested your demo page).

**Comment by dixso** [comment]
Solved in this version:
https://github.com/dixso/custombox/commit/61fd0ab5789ab9b26f004cdfa898903f1485a3f5
