### ISSUE TITLE
Open modal window without trigger

### ISSUE THREAD

**Issue by JoanIzquierdo** [dixso/custombox#164]
Do you know how I can open the modal window without invoke trigger? 

			$('#opendialog').on('click', function( e ) {
				Custombox.open({
					target: '#modallogin',
				});
				e.preventDefault();
			});

			$('#opendialog').trigger( "click" );			

Thanks.

**Comment by dixso** [comment]
Hi Joan,
```
$(function(){
   Custombox.open({
       target: '#modallogin',
   });
});
```

**Comment by JoanIzquierdo** [comment]
Thanks dixco!
