### ISSUE TITLE
Jumps

### ISSUE THREAD

**Issue by Rinkana190** [dixso/custombox#165]
Hi there,

I'am using your extension to display all modal windows on the site, and I've found a bug or smth wrong,
when user scroll page to the end(scrollbar is down) there is some move(width of scrollbar about 19px) in horizontal plane, but when I show modal at the top/middle of the page everything is ok and works fine.

It moves in IE10.

Thanks for extension.

**Comment by dixso** [comment]
Hi,
Try the new RC: https://github.com/dixso/custombox/tree/master/dist
Regards
