### ISSUE TITLE
Second modal re-opening

### ISSUE THREAD

**Issue by add-nova** [dixso/custombox#166]
Hi! First of all - yor plugin is tottally awesome)
But I've found, that when I try to reopen second modal window it doesn't open :(
If try to describe with your exmple of ininity modals, action chain is:
Open example -> click "Open other modal" -> close second modal -> click "Open other modal" and it does'n work (at least for me, tried it on http://dixso.github.io/custombox/ page) :(
Tested in Firefox and Chrome.

Thank you so much for your plugin!

**Comment by villbe** [comment]
You need to close all modal before re-opening it.

Follow these steps: Open modal 1 -> open modal 2 -> close modal 2 -> close modal 1 -> open modal 1 -> open modal 2...

It should work :)

**Comment by kstein** [comment]
as far as I can tell, the event that closes the modal when you click on the overlay is interfering. It needs to include logic to ignore click events originating inside the modal. here's what I did as a quick jQuery fix (starting at line 679)
`            // Overlay close.
            cb.wrapper.event = function ( event ) {
				if (!$(event.target).closest('.custombox-modal-container').length)
				{
					if ( _this.cb.length === 1 ) {
						document.removeEventListener('keydown', cb.wrapper.event);
					}
					if ( !stop && event.target === cb.wrapper && _this.get() && _this.get().settings.overlayClose ) {
						stop = true;
						_this.close();
					}
				}
            };`

**Comment by jigsdatta** [comment]
Hi,
I am also getting the same error when try to reopen the modal again in multiple modals.
@kstein  : Can you please elaborate more details for your fix code? I am not finding the line no 679 on Custombox js file. So can you plese let me know where should I actually place your fix code?

**Comment by dixso** [comment]
Hi,
I'm doing the new version and will solve many bugs and some improvements.

**Comment by jigsdatta** [comment]
Hi dixso,

Thank you for your support. Please let me know when you release a new version.

**Comment by dixso** [comment]
Hi,
Could you check the new release of Custombox?
Regards!
