### ISSUE TITLE
Scrolling to top on modal open

### ISSUE THREAD

**Issue by tomheaps** [dixso/custombox#169]
Please look at my page preview at https://preview.c9users.io/tomheaps/amu2016/documents.html?_c9_id=livepreview0&_c9_host=https://ide.c9.io 

The button to activate the modal is at the bottom left of the page, just above the footer.

Is there any way to prevent the page from scrolling to the top when you click on the button to open this test modal?

I have looked through previous issues with scrolling to top and tried adding 'height:auto' to .custombox-open body and .custombox-perspective body in the CSS but this has no effect.

Thanks.

**Comment by tomheaps** [comment]
I have found a solution to the problem I was describing which is to include the entire content of your page in a container div and ensure that the html for the modal sits outside of this container div - please consider including these instructions in your readme file so other users don't run into the same issues I had. 

On a separate note I have found a bug which is evident on your demo page and affects the latest 2 transitions at the bottom - 'flash' and 'swell' - once modal is open with these effects you cannot click on the cross to close the modal and the only way of closing it is to click on the modal overlay?

**Comment by ijakparov** [comment]
I have the same issue, but separate container didn't help.

**Comment by LuisEGR** [comment]
Here the same, I load elements with infinite scroll and there are a lot of them, but when you click one to see its modal the scroll goes to the top, which is not what I want.

**Comment by ijakparov** [comment]
Try to remove height:100% from html,body in your css

**Comment by guizoxxv** [comment]
The container solution didn't work for me. Removing 100% height fixed the issue but it wasn't a solution as it breaks my page layout.

**Comment by dixso** [comment]
Hi,
I'm working with a new version (in the coming weeks).
Regards!

**Comment by dixso** [comment]
Hi,
Try the new RC: https://github.com/dixso/custombox/tree/master/dist
Regards
