### ISSUE TITLE
ASP.NET button inside custombox modal not triggering click event

### ISSUE THREAD

**Issue by noth50** [dixso/custombox#171]
Hi im working with custombox modal in my asp.net site, modal is working fine but the button BTNConfirm_Click inside modal footer is not firing click even

I have no problem with opening modal I have problem with button (BTNConfirm_Click) inside modal footer is not firing click even (OnClick )

My function for call modal:

    <script>
    $(function Modal() {
        $('#LkForget').on('click', function (e) {
            Custombox.open({
                target: 'Page/ForgotPassword.aspx',
                effect: 'fadein'
            });
            e.preventDefault();
        });
    });
</script>

**Comment by dixso** [comment]
Hi,
```javascript
<script>
    $(function Modal() {
        $('#BTNConfirm_Click').on('click', function (e) {
            Custombox.close();
            e.preventDefault();
        });
    });
</script>
```
