### ISSUE TITLE
Changing properties dynamically after open is done, possible?

### ISSUE THREAD

**Issue by adgsm** [dixso/custombox#172]
Hi, how can I change properties dynamically following open is done? Thanks

**Comment by dixso** [comment]
Hi,
Do you mean when close the modal?

**Comment by adgsm** [comment]
Hi,
Thanks for your answer. No, I mean for example when modal is open, could it be possible to change some property value dynamically (e.g. overlayClose property value from true to false, etc...).
Thanks once again for your answer.
Regards

**Comment by dixso** [comment]
Hi,
I'm sorry but isn't possible because custombox is initialized for multiple instances.
Regards.

**Comment by adgsm** [comment]
thanks
