### ISSUE TITLE
 Custombox refresh the page to close the modal .

### ISSUE THREAD

**Issue by eduardoexplod** [dixso/custombox#173]
Hello I am working with Custombox in a portal Liferay Portal , the only question that has arisen me is whether you can remove the effect that occurs when you close the window, because in this moment I reload the page , I would like that did not happen . Is there a way to disable the page to reload the close the window?

`                $JQuery_Mod(document).ready(function() {
                    $JQuery_Mod('.list-group-item').on('click', function( e ) {
                        Custombox.open({
                            target:     this.getAttribute('href'),
                            effect:     'flip',
                            close :     function(){ stopAll(); }
                        });
                        e.preventDefault();
                    });
                }); `

**Comment by dixso** [comment]
Hi,
The only solution is modify the CSS class, for example:
https://github.com/dixso/custombox/blob/master/src/css/custombox.css#L250
