### ISSUE TITLE
deletes iframe content

### ISSUE THREAD

**Issue by Alebqto** [dixso/custombox#174]
to open the window , delete the contents of my twitter widget . any suggestions?

**Comment by dixso** [comment]
You have any problems with custombox?

**Comment by Alebqto** [comment]
I think it's a bug, running custombox in a modal window and affected an iframe ( widget twitter ) as in the index

**Comment by dixso** [comment]
Hi,
Try this:
`Custombox.set({
  autobuild: true
});
document.getElementById('element').addEventListener('click', function( e ) {
  Custombox.open({
      target: '#modal',
      effect: 'fadein'
    });
  e.preventDefault();
});`
