### ISSUE TITLE
Error to open a new customBox

### ISSUE THREAD

**Issue by jos1202** [dixso/custombox#178]
Hi, in the version 3.0.2, when click on this the following message apears this error: "Uncaught TypeError: undefined is not a function".
My version of Windows is 7 and Google Chrome is 40.
This is my code:
function OpenMenu() {
                    width = (screen.width * 70) / 100;
                    Custombox.open({
                        target: '#MenuTool',
                        effect: 'slit',
                        id: "MenuTool",
                        width: width,
                        overlaySpeed: 1200,
                        position:['center','center']
                    });
                }

Thanks

**Comment by dixso** [comment]
Hi,
You could put your code in jsfiddle.net?
