### ISSUE TITLE
Swell effect mobile close not working

### ISSUE THREAD

**Issue by ericjlars** [dixso/custombox#181]
If using the 'Swell' effect, the close works fine on the desktop. But if you try with phone, the box closes, but the black overlay does not. Any idea on how to fix this?

Using code:

$(function() {
        $('#register').on('click', function( e ) {
			Custombox.open({
                target: '#modal',
                effect: 'swell'
            });
			e.preventDefault();
        });
    });

**Comment by dixso** [comment]
Hi,
Shouldn't do it.
Can you put a example in jsfiddle?

**Comment by Damian89** [comment]
I do have the same issue with all new effects on webkit browsers. No problems with other effects like flip.
