### ISSUE TITLE
Open a set of Images with custombox

### ISSUE THREAD

**Issue by drmAbused** [dixso/custombox#182]
Hi,

I simply love your blur effect ;)

I was wondering if there is a possibility of opening a set of images via custombox, just like in the lightbox2 if the links have the same "lightbox-data" attribute, it opens all of them in a gallery where I can switch back and forth between the images. You probably know what I mean but just to be sure see here: http://lokeshdhakar.com/projects/lightbox2/

I'm talking about the "Four image set" on the website of lokesh dhakar.

best regards and thx
mlp

**Comment by dixso** [comment]
Repeated: https://github.com/dixso/custombox/issues/155
