### ISSUE TITLE
Not working into IPhone and windows safari

### ISSUE THREAD

**Issue by SIDROCK** [dixso/custombox#185]
Hello, 

I m using custombox but in IPhone and windows safari it is not working also browser hanged sometimes in both here is my code .... also in windows safari all effects are not working check our demo site ..

 **var target = "#" + (viewData.divId);
            Custombox.open({
                id : 'custombox_' + (viewData.divId),
                target: target, //href, //selector.custombox_show_images_target,
                effect: 'fadein',
                overlaySpeed: 100,
                speed: 200,
                width: 1400,
                close: function () {
                    //console.log(target);
                    var targetToRemove = $(target);
                    targetToRemove.remove();
                }
            });**

please help me its urgent

**Comment by adrianratajczak** [comment]
Please dont use Safari browser for Windows. It's too old.

**Comment by SIDROCK** [comment]
But what about IPhone? it has V 9.0

**Comment by SIDROCK** [comment]
I m creating dynamic HTML using javascript and then set that html as popup  with

**"#" + (viewData.divId);**

so in all browser and mobile its working but in IPhone browser hanged when i open this popup....

**Comment by dixso** [comment]
Hi,
I checked with my iphone and it works.

**Comment by SIDROCK** [comment]
Can u check in mac book and send me screenshot for iphone and mac book both.as i already tell u that i m creating dynamic HTML for this popup... Thanks for reply

**Comment by xForMe** [comment]
I meet same problem , in iOS 8.3 is ok  but in 9.32 not work

**Comment by siliconalchemy** [comment]
On iphone4, iphone5s and ipad air, they all open a modal and then close it again immediately.  Using Custombox.open() to open it.

**Comment by SIDROCK** [comment]
attached the screenshot when i open the cutombox my safari bowser hanged in my Iphone 6 

![image](https://cloud.githubusercontent.com/assets/16042087/16584091/61fd049a-42d7-11e6-83d4-9392b45a1be3.png)

**Comment by dixso** [comment]
Hi,
Thanks for your reports, I'll investigate.
