### ISSUE TITLE
Sequence: Opening A Opening B Closing B Opening B Closing B doesn't work

### ISSUE THREAD

**Issue by RedAdder** [dixso/custombox#187]
I have two dialogs #A and #B where dialog #B can be reopened multiple times from #A.

The existing custombox code at some point then has 2 elements, but the item counter gets increased to 3 which is out of range. I suggest this code change, which works fine for me: 

        set: function( val ) {
            if ( !this.cb || !this.cb.length ) {
                this.cb = [];
            }

            this.item = this.cb.length;
            ....

**Comment by dixso** [comment]
Hi,
PR are welcome :)
