### ISSUE TITLE
Custom Box not working in Safari browser

### ISSUE THREAD

**Issue by paulvaskar** [dixso/custombox#192]
I have implemented the custom box in one of my application. It is working properly in Chrome and Firefox. But when I am trying to open it in Safari or in the default android mobile browser, it is showing me the following error.

TypeError: 'undefined' is not a function (evaluating 'Object.assign({},a,c)')

Please suggest what should I do to resolve the issue.

Also I tried to open the following URL in safari and run the demo provided here - it is not working. But according to the specification given here it should work in safari also.

http://dixso.github.io/custombox/

Please provide suggestion how to resolve these issues in Safari browser?
I am using Safari version 5.1.7 on windows 7

**Comment by dixso** [comment]
Hi,
Thanks for your report, I'll investigate.
