### ISSUE TITLE
Chained Lightbox Bug

### ISSUE THREAD

**Issue by vaibhavbhanushali** [dixso/custombox#193]
There's a problem when multiple Custombox are opened. 
For ex:- 
I click a button in site, which opens Custombox_1 
Within Custombox_1, theres an another button which opens Custombox_2, 
Now i close Custombox_2  and then again click the same button within Custombox_1 which opens custombox_2. 
This time it doesn't works and gives some error like settings undefined.
I was able to replicate the bug in jsfiddle. 
Do this to see the bug 
-Click Open CB 1
-Click Open CB 2
-Close CB 2
-Open CB 2 (it won't open)

https://jsfiddle.net/ecbghbwg/1/

**Comment by dixso** [comment]
Hi,
Could you check the new release of Custombox?
Regards!
