### ISSUE TITLE
turning animation off

### ISSUE THREAD

**Issue by barbedCoil** [dixso/custombox#196]
Not a bug per-se but sometimes its just nice to not have all the flash in a business app - any way to turn animation off?  tried increasing speed to 900 - took forever - turning it to 0 did even worse

**Comment by barbedCoil** [comment]
sorry for the long delay in noticing this - was this feature added to v4.x RC?

**Comment by dixso** [comment]
Hi @barbedCoil,
Yeah, you can use `speedIn` and/or `speedOut ` options.
Regards!

**Comment by barbedCoil** [comment]
thanks. appreciate the reply

On February 2, 2017 11:23:41 PM MST, Julio de la Calle <notifications@github.com> wrote:
>Hi @barbedCoil,
>Yeah, you can use `speedIn` and/or `speedOut ` options.
>Regards!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dixso/custombox/issues/196#issuecomment-277173859

-- 
Tab
