### ISSUE TITLE
Visual glitch while running the modal

### ISSUE THREAD

**Issue by Mhmdshv** [dixso/custombox#197]
Hi,
My homepage includes a lot of 3d transformed objects and images, and when i try to open the modal i will see a lot of visual glitches when the modal is opening and closing. I noticed that Custombox moves the entire body elements into a separate DIV. I manually changed the page's elements to it's default by using inspect elements, and everything was fine.

I was wondering if i can stop Custombox from moving every element to a separate DIV.

I already tried to mess with this line of code but no use: 

`for(var f=document.querySelectorAll(".custombox-container > *"),g=0,h=f.length;h>g;g++)document.body.insertBefore(f[g],c.main);c.main.parentNode&&c.main.parentNode.removeChild(c.main),delete c.main`

Any help is appreciated.

**Comment by dixso** [comment]
Hi,
Comment this line:
https://github.com/dixso/custombox/blob/master/src/js/custombox.js#L134-L136
Regards!

**Comment by Mhmdshv** [comment]
Thank you, this almost did what i want. but there is a small problem now. 

After closing the modal, the overlay will not be removed. there is still a DIV with a class of `custombox-overlay custombox-overlay-fadein custombox-overlay-default` covering the entire page. 

Is there a way to remove that too?
Thanks again for supporting.

**Comment by Mhmdshv** [comment]
Hi again,
I changed this line of code:
`for (this.main = document.createElement("div"); document.body.firstChild;) `

into this:
`this.main = document.createElement("div");`

and it solved the issue. I wonder if this will have any side effects on how customBox will work?

**Comment by dixso** [comment]
Hi,
In the next release I resolve it this.
https://github.com/dixso/custombox/tree/develop
Regards!
