### ISSUE TITLE
provide document for Previous versions

### ISSUE THREAD

**Issue by spostad7** [dixso/custombox#208]
hi,
I had some trouble in my code with the new release. The plugin does not run slimScroll.js on open modal and I had to use previous version and it worked fine. Also it had issue when I wrote onOpen method in options in data-custombox.

here is my code that return dispatch error:
```
<button type="button" data-custombox='{"content":{"effect":"fadein","target":"#forward-pm","width":"380px","delay":"100","onOpen":"scroll_list();console.log("hello");"},"overlay":{"color":"#707070","opacity":".5"}}' class="btn btn_yellow send-tool__forward-btn">forward</button>
```
and here is scroll_list():
```
function scroll_list() {
    $(".popover__list").slimscroll({
        width: "100%",
        height: "300px",
        color: "#fae28f",
        size: "5px",
        distance: "5px",
        opacity: 1,
        position: "right",
        alwaysVisible: 1,
        disableFadeOut: !0,
        railVisible: !0,
        railColor: "#faf1d3",
        railOpacity: 1
    });
}
```

**Comment by dixso** [comment]
Hi,
But why you use `data-custombox`? Is just a demo.
You must use a simple code:
```javascript
// Instantiate new modal
var modal = new Custombox.modal({
  content: {
    effect: 'fadein',
    target: '#modal',
    onOpen: function() {
     $(".popover__list").slimscroll({
        width: "100%",
        height: "300px",
        color: "#fae28f",
        size: "5px",
        distance: "5px",
        opacity: 1,
        position: "right",
        alwaysVisible: 1,
        disableFadeOut: !0,
        railVisible: !0,
        railColor: "#faf1d3",
        railOpacity: 1
      });
    }
  }
});

// Open
modal.open();
```

By the way if the class `popover__list` is in your modal you must use the callback `onComplete`.
Regards!

**Comment by spostad7** [comment]
tanx, it works now, the box will scroll after modal Complete; 
but it only work for the first time that modal appear. for next times it stop working (stop scrolling). maybe it has some issue with callback function, because when I used v3.0.2 with same setting everything worked fine...

**Comment by dixso** [comment]
Hi,
Could you put an example in jsfiddle?
