### ISSUE TITLE
Custombox popup not working in IE11

### ISSUE THREAD

**Issue by bharatj02** [dixso/custombox#209]
Hi,

Thank you for the amazing plugin. 

I have recently upgraded the custombox version to 4.0.0 and came up with the following issues.

1. Modal popup not working in IE11 and throwing the following error

![image](https://cloud.githubusercontent.com/assets/18543840/22303189/17ec94fa-e300-11e6-80e6-f372ec020792.png)

2. Content not resizing in mobile (tested in Iphone 6). I can provide more details if needed.

One again Thank you for the nice plugin

**Comment by dixso** [comment]
Hi @bharatj02,
Thanks, I'll investigate it.

**Comment by bharatj02** [comment]
Hi @dixso,

I am able to fix the IE issue by changing "new event()" to "new CustomEvent()" and using the polyfill in the following link (did not test with the old polyfill)
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent 

But I could not figure out the issue with mobile resizing. I am loading content dynamically and resizing works fine in desktop browser, when I switch to mobile browser it changes width to 200% and random height (might be with the dynamic content). I could not figure out the dynamic calculation. 

Thank you

**Comment by dixso** [comment]
Hi @bharatj02,
I [replace](https://github.com/dixso/custombox/commit/60891b0ade7c554d367a5fb6e035603a9efe62fb) the Event constructor by the CustomEvent.
The funny thing is that I already put the file [before](https://github.com/dixso/custombox/blob/master/Gruntfile.js#L47-L56).

Could you put an example in jsfiddle.net to give me an idea.
Regards.

**Comment by bharatj02** [comment]
Hi dixso,

Please check this fiddle - https://jsfiddle.net/a46jnv9k/1/

It has the dumb down version of what I am trying to achieve. Everything works fine in desktop browser but when I change to mobile width & height calculations are going off.

Thank You

**Comment by dixso** [comment]
Hi,
I haven't been able to check it with a cell phone yet.
But is possibly the problem was the _col-xs-12_ class?
`<div class="col-xs-12 demo-modal">`

Can you delete that class?
`<div class="demo-modal">`

Regards.

**Comment by bharatj02** [comment]
Hi,
Col-xs-12 is not the issue. Same code is working fine if I change the screen size to smaller size in regular browser. I think it might be something to do with transform css or screen height/width calculation for mobile screens.

**Comment by dixso** [comment]
I'm sorry but I don't understand your problem...

I just checked with my mobile and works done.
Maybe the example isn't correct?

**Comment by bharatj02** [comment]
Hi,

I have checked my application again and able to pinpoint the issue. Problem is with the Viewport metatag and only causing issues with Push effect and SlideInLeft transition. After updating the metatag everything worked fine. 

I really appreciate your time and help on this.

**Comment by dixso** [comment]
You're welcome!
Don't forget give me a star! :simple_smile:
