### ISSUE TITLE
Tab Key Press on Modal Popup

### ISSUE THREAD

**Issue by bharatj02** [dixso/custombox#210]
Hi,

When I press tab key it moves the focus on to controls outside modal popup. With push effect it is showing the pushed content on tab press. Same issue exists in your Live website. Let me know if you need aditional information.

Javascript to move the focus from last control to first control inside modal popup worked in chrome but not in IE and firefox. 

Again Thank you for the amazing plugin

**Comment by dixso** [comment]
Hi @bharatj02,
Why it close the issue?

**Comment by bharatj02** [comment]
I have checked other modals and most of them have the same issue, so I I thought issue is not in the scope of custombox js and closed it. I did some research and came up with a solution to avoid this issue. 
I am posting it if it helps

I have created two methods. First method is to update the tabindex of all the controls outside modalpopup to -1 and store the current tabindex into an attribute. This method runs on custombox open action

```
function FixTabPressModalPopup()
{
    
    inputs = $(".custombox-content .modal-wrapper").find('select, input, textarea, button').filter(':visible');
    firstInput = inputs.first();
    lastInput = inputs.last();

    /*redirect last tab to first input*/
    lastInput.on('keydown', function (e) {
        if ((e.which === 9 && !e.shiftKey)) {
            e.preventDefault();
            firstInput.focus();
        }
    });

    /*redirect first shift+tab to last input*/
    firstInput.on('keydown', function (e) {
        if ((e.which === 9 && e.shiftKey)) {
            e.preventDefault();
            lastInput.focus();
        }
    });

    // Change all other controls tabindex to -1 
    // Store the current tabindex into an attribute
    var allinputs = $(":tabbable");
    var disabletabinputs = allinputs.not(inputs);
    disabletabinputs.each(function (index) {
        
        $(this).attr('data-original-tab-index', $(this).attr('tabindex'));
        $(this).attr('tabindex',-1);
      
    });  
    
    ///*set focus on first input*/
    firstInput.focus();  

}
```

Second method is to re create the tabindex from custom attribute and this runs on close method

```
function LoadOldTabIndex()
{
    $("[data-original-tab-index]")(function (index) {

        $(this).attr('tabindex', $(this).attr('data-original-tab-index'));
    });
}

```

**Comment by dixso** [comment]
Hi @bharatj02,
Do you think it would be interesting to apply it?
We could add another independent issue.
