### ISSUE TITLE
Multiple Custombox Management

### ISSUE THREAD

**Issue by shaan82** [dixso/custombox#217]
Hi,

I have a scenario where I need to forcefully popup the custombox to the user in certain conditions. But on the same page, there are some of the divs, by clicking on them, will show another custombox with different details. But theres a conflict in between these two, as when the forced custombox tried to appear on load, and on the same time user clicks on the custombox div on page, somtimes the page gets stuck with the faded screen, otherwise multiple popups open on one another. 

Is there any way we can lock the custombox, not to let any other custombox open, unless the current one is there. We cannot use the close method while opening the new one because this will not be the case always.

Thanks.

**Comment by dixso** [comment]
Hi,
Could you put an example in jsfiddle.net?
