### ISSUE TITLE
Javascript .value method dont work while form is inside modal.

### ISSUE THREAD

**Issue by robbieservices** [dixso/custombox#218]
So bascilly .value method always return null while my form is inside custombox modal.

If you want to look inside code check my stackoverflow post : 

http://stackoverflow.com/questions/42880106/javascript-with-ajax-values?noredirect=1#comment72864170_42880106

Cheers

**Comment by dixso** [comment]
Hi,
I have already [answered](http://stackoverflow.com/a/42884278/3190151).

Regards.

**Comment by robbieservices** [comment]
Hello, check my answer.

Regards.

**Comment by robbieservices** [comment]
Hey, can you debug it live? Since i have no idea how to upload custombox at jsfiddle rofl.

http://robbieservices.e-kei.pl/

Just open contact form (bottom of page "Get started buttton") and try in dev console _("n").value

Cheers, i can play with jsfiddle if necessary

**Comment by dixso** [comment]
I'm sorry but if you don't put an example (for debugging later) on jsfiddle.net, I can't help you.
