### ISSUE TITLE
How do I leave the scroll?

### ISSUE THREAD

**Issue by avconsbn** [dixso/custombox#219]
Hi,
Custombox is open.
Scrolling disappears, the window jumps to the right.
How do I leave the scroll?
Sorry for my english.
Thanks

**Comment by dixso** [comment]
Hi,
Could you put a example in [jsfiddle.net](https://jsfiddle.net)?

**Comment by avconsbn** [comment]
Hi,
Bootstrap 3.3.7, jQuery 3.1.1
```
$('#openModal').on('click', function( e ) {
Custombox.open({
target: '#myModal',
effect: 'door'
});
e.preventDefault();
});
```
Custombox is open. Scrolling - none.
Custombox is close. Scrolling - yes.
Result - jumps to the right.

Sorry for my english.
Thanks

**Comment by avconsbn** [comment]
See here. jumps to the right. dixso.github.io/custombox/
[](http://dixso.github.io/custombox/)

Windows 8. Opera, FireFox.

**Comment by dixso** [comment]
Ok, thanks.
I'll fix it!

**Comment by dixso** [comment]
Hi,
Solved: https://github.com/dixso/custombox/releases/tag/4.0.1

Thanks!
