### ISSUE TITLE
Confirmation of required files for custombox

### ISSUE THREAD

**Issue by extend1994** [dixso/custombox#225]
Hi
I am a member of CDNJS and the one in charge of adding your library according to cdnjs/cdnjs#10669.
I am wondering if `custombox.legacy.min.js` in v4.0.0 is required. In README.md of v4.0.0, it said

> download the package and reference the JavaScript and CSS files manually:
\<script src="dist/custombox.min.js"></script>
\<link rel="stylesheet" type="text/css" href="dist/custombox.min.css">

But before v3.0.2, you mentioned that 

>Make sure to also include the legacy.js file along for the older browsers.
\<script src="legacy.min.js"></script>

Can you please tell me if we need `custombox.legacy.min.js` to let custombox work well?

Thank you!

**Comment by dixso** [comment]
Hi @extend1994 ,
The legacy file include all of polyfills necessary for the legacy browsers.

**Comment by extend1994** [comment]
@dixso Thanks a lot again!

**Comment by extend1994** [comment]
Hi @dixso 
Sorry about bothering you again. `custombox.legacy.min.js` seems not a really minified file. If the library doesn't have officially minified file(s), CDNJS will minify it (or them) but the file format can not be `library.min.js`(something like that). Is it possible for you to change the naming scheme? For sure you can choose to minify them on your own :smile:

**Comment by dixso** [comment]
Hi @extend1994,
Solved: https://github.com/dixso/custombox/releases/tag/4.0.1

Thanks a lot!
