### ISSUE TITLE
Element access problem.

### ISSUE THREAD

**Issue by ferhatyesilmen** [dixso/custombox#226]
Hi,

After opening the custombox, the elements are not accessible.

Ex:
`$('#table1').hide(); // not working.`

https://jsfiddle.net/rcd0zh95/1/

**Comment by dixso** [comment]
Hi,
The problem is because custombox duplicate it the element and need to remove the ID attribute for avoid duplicates in the DOM.

I'm not sure what is the best way to solve it...

**Comment by rajakhoury** [comment]
Yes, noticed that in V4 DOM elements are duplicated. 
Is there a way to prevent this behavior ?
This doesn't place nice for example with Bootstrap tabs or forms elements.. 
There are many cases where u need to keep the IDs..

**Comment by dixso** [comment]
Duplicate: https://github.com/dixso/custombox/issues/230
