### ISSUE TITLE
content esckey=false and layout close=false is not preventing modal to close

### ISSUE THREAD

**Issue by lkallas** [dixso/custombox#227]
The following setup does not prevent modal to close on overlay click or ESC key event. According to doc it should not close if modal set up this way.

`new Custombox.modal({
  content : {
    effect: 'fadein',
    esckey: false
  },
overlay : {
    close: false
  }
});`

**Comment by dixso** [comment]
Hi,
Could you put an example in [jsfiddle.net](jsfiddle.net)?

Regards

**Comment by lkallas** [comment]
Example here: [https://jsfiddle.net/xpkx86t5/2/](url)

**Comment by dixso** [comment]
Yeah, is a bug.
I'll fixit in the next release.

**Comment by dixso** [comment]
Hi @lkallas,
Solved in the next release (coming soon).

Regards.
