### ISSUE TITLE
Not able to get value of the form elements

### ISSUE THREAD

**Issue by paragajency** [dixso/custombox#230]
Hi, if i change the value of input texxt box, and press the button, not able to get value of text box .
See the js fiddle http://fiddle.jshell.net/t5S3c/40/show/

**Comment by dixso** [comment]
Hi @paragajency ,
I think is a bug, I'll check it.

Regards.

**Comment by paragajency** [comment]
I guess it duplicates the modal, and as such duplicates the form/elements too.
Cant the modal work without duplicating itself and the content?

**Comment by dixso** [comment]
Hi @paragajency  ,
Solved in the next release (coming soon).

Regards.
