### ISSUE TITLE
jquery.js:3855 Uncaught TypeError: Custombox is not a constructor

### ISSUE THREAD

**Issue by vladi160** [dixso/custombox#234]
jquery.js:3855 Uncaught TypeError: Custombox is not a constructor
with this code from site and included CSS and JS: 
`    var modal = new Custombox({
       content: {
           affect: 'fadeiin',
           target: '#askModal'
       }
    });
    modal.open();`

Is this library still supported and how to fix the error?

**Comment by dixso** [comment]
Hi,
Could you put an example in [jsfiddle.net](jsfiddle.net)?

Regards
