### ISSUE TITLE
Responsive Widths

### ISSUE THREAD

**Issue by mappinsc** [dixso/custombox#235]
I am using the following for my custombox settings. Though setting the width as 550 makes the modal no longer responsive.

```
$('#example').on('click', function () {
    $.fn.custombox( this, {
        effect: 'fadein',
        loading: true,
        width: 550
    });
    return false;
	});
```

I noticed the examples on this page are not responsive either http://www.jqueryscript.net/demo/Responsive-jQuery-Modal-Window-Plugin-with-CSS3-Transitions-Custombox/.

Is this something that can be fixed? Thank you!

**Comment by dixso** [comment]
Hi,
This version is obsolete, please use the new version of Custombox.
Regards.
