### ISSUE TITLE
"Error: The ajax response need a wrapper element" after the update

### ISSUE THREAD

**Issue by JackJohansson** [dixso/custombox#236]
Hi,
I've been using this plugin for a while, and decided to update it to the latest version. After the update, it stopped working. When i click the button, i see the loading animation for a second, and then it disappears and i get this error in the console:

> Error: The ajax response need a wrapper element

The AJAX response is wrapped in a DIV. I also tried to set the container but no avail.

I didn't modify anything, except replacing the old files with new ones, and this old code:

```
Custombox.open({
	target: url,
	effect:'fadein',
});
```

With the new one:

```
new Custombox.modal({
		content:{
			effect: 'fadein',
			target: url
		}
	}).open();
```

How can i solve this issue?
Regards,
Jack

**Comment by dixso** [comment]
Hi @JackJohansson,
You need to wrap a div into the ajax file.
```html
<div>some ajax</div>
```

Regards.

**Comment by JackJohansson** [comment]
Hi! 
Thank you for the reply. 

If you mean the response, then my AJAX response is already wrapped in: `<div id="ajaxcontent"></div>`

[Here](http://wallpaperinho.com/wp-admin/admin-ajax.php?action=photogram_ajax_handler&post_id=7821&nonce=d01c801056) is a link to one of my AJAX responses. you can check the HTML output, and see that the response is in a DIV .

Unless you meant to wrap the javascript target in a DIV...

**Comment by dixso** [comment]
Hi!
Yes, you need to wrap it.
Put an example into http://jsfiddle.net/

Regards

**Comment by JackJohansson** [comment]
Never mind, I rolled back to an older version. Version 4 doesn't seem to support SpinKit either. Thanks for both support, and this cool plugin :)

**Comment by JackJohansson** [comment]
Never mind, I rolled back to an older version. Version 4 doesn't seem to support SpinKit either. Thanks for both support, and this cool plugin :)
