### ISSUE TITLE
Split custombox.scss into core and effects files

### ISSUE THREAD

**Issue by scarfacedeb** [dixso/custombox#237]
Have you considered splitting the custombox.scss into core and effects files?

It'd allow to import only core styles for some users, to avoid having a lot of unwanted css for effects that they're not using.

Moreover, you can store each effect in its own file, giving the user a way to only import the effect that he's using.

I've tried to fork the project and refactor it by myself, but I was unable to run the build process. (`npm start` started the browsersync, but localhost:3001 only rendered the `GET /` error, `grunt dist` also stopped with `Aborted due to warnings.`).

**Comment by dixso** [comment]
Hi @scarfacedeb,
If you do a PR are welcome!

The "error" is because you need to put a index file into the src directory.

Reagards
