### ISSUE TITLE
Error when install with Bower on .NET Core

### ISSUE THREAD

**Issue by vladi160** [dixso/custombox#241]
> Severity	Code	Description	Project	File	Line	Suppression State
Error	TS18003	Build:No inputs were found in config file 'C:.../wwwroot/lib/custombox/tsconfig.json'. Specified 'include' paths were '["src/*"]' and 'exclude' paths were '["node_modules"]'.	Hydra.WebUi	C:...\tsc	1

**Comment by dixso** [comment]
Hi @vladi160 ,
Sorry but I don't understand what you're trying to do.
