### ISSUE TITLE
Rotate Custom Animation not animating on close

### ISSUE THREAD

**Issue by mediadr** [dixso/custombox#84]
Thanks for the latest updates to this.
The effect I was liking the most was rotate, with animation hints of 'left,right'. It works in the old one fine, but its a bit buggy in the new version. It will animate in properly, but it won't animate out properly.

First is modifies the size of the modal window, it seems to grow horizontally. Then the overlay fades out and the window makes a hard exit.

**Comment by dixso** [comment]
Hi,
Can you insert your code in jsfiddle.net?
Because I don't understand you.
Thanks!
