### ISSUE TITLE
Unwanted reloading of Flash files

### ISSUE THREAD

**Issue by mediadr** [dixso/custombox#85]
is it possible to add an option to have it NOT reload swf files upon modal close? It is causing a few undesirable effects like flashing a white box in the swf zone, and timeline animations make it very obvious it reloaded the swf.

I've been combining this modal with some Flash special effects to really make some eye popping modals and preloaders. They look way better than anything in HTML5.

**Comment by dixso** [comment]
Hi,
Can you insert your demo in jsfiddle.net?
Thanks!

**Comment by mediadr** [comment]
Yes, it's going to take me a moment though, I have to make a demo of the problem when I get a chance

It's pretty simple to put in words though, everytime the modal is triggered, either closed or open, it refreshes swf files. When it does this, the animations start all over again.
