### ISSUE TITLE
Overlay of the custombox

### ISSUE THREAD

**Issue by chrifmarwen** [dixso/custombox#86]
Hi,

There is a difference between : overlay;false and overlayOpacity:0 ?
I used overlay;false to remove the overlay but it dosn't what i expect, it just make it transparent.
There is a trick to remove the overlay ?

Thinks.

**Comment by dixso** [comment]
Hi,
Try this:
overlay: false
overlayClose: false

Regards.

**Comment by chrifmarwen** [comment]
I have already tried this @dixso.

I made a fiddle to show you the problem :

http://jsfiddle.net/chrifmarwen/xwc9h9py/1/

**Comment by dixso** [comment]
Ah!
I'm sorry but not possible because there is a wrapper div "custombox-modal-wrapper".
It is used to prevent scrollbar in the window.
