### ISSUE TITLE
Bug closing modal

### ISSUE THREAD

**Issue by chrifmarwen** [dixso/custombox#87]
Hi,

when i close the custombox it dosn't make it display:none.

there is a demo :

http://jsfiddle.net/chrifmarwen/Anj4s/21/

regards.

**Comment by mediadr** [comment]
I ran into this and worked around it by first applying display:none; to the css of the modal div class instead of doing it on the element to initially hide it.

**Comment by dixso** [comment]
Added into the new release:
https://github.com/dixso/custombox/releases/tag/2.2.2
Regards.
