### ISSUE TITLE
Cannot Open in IE 9

### ISSUE THREAD

**Issue by spryguy** [dixso/custombox#90]
No matter what I try in IE 9 on Windows 7 I cannot get a custombox to open with the following error.  My code is included below and the version I'm using is 2.2.1.

SCRIPT5007: Unable to set value of the property 'custombox': object is null or undefined 
custombox.js, line 132 character 17

<!DOCTYPE html>

<html>
    <head>
        <title>Test</title>
    </head>
    <body>

        <div>
            <div id="entries" class="news-posts">
                <button class="show-blog-detail" >Open</button>
            </div>
            <br /><br />
            <div id="detail">
                Blog Detail
            </div>
        </div>
        
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.3.js"></script>
        <script type="text/javascript" src="//cdn.polyfill.io/v1/polyfill.js"></script>
        <script type="text/javascript" src="~/Content/Scripts/Blog/custombox.js"></script>

        <script type="text/javascript">
            $(function() {
                $(".show-blog-detail").on("click", function (e) {
                    Custombox.open({
                        target: "#detail"
                    });
                    e.preventDefault();
                });
            });
        </script>
    </body>
</html>

**Comment by dixso** [comment]
Hi,
Solved in this release:
https://github.com/dixso/custombox/releases/tag/2.2.3

Remember, remove the polyfill.js and add legacy.min.js.
Regards.
