### ISSUE TITLE
IE 11 SCRIPT5022: SyntaxError

### ISSUE THREAD

**Issue by tsok** [dixso/custombox#94]
Use in my project latest ver. of custombox (2.2.3)
Error occures on IE 11 and ipad after simple actions like:
            $('#regbtn').on('click', function (e) {
                Custombox.open({
                    target: '#modal',
                    effect: 'fadein',
                    zIndex: 999
                });
                e.preventDefault();
            });

legacy.js also included
error supposedly in: g=d.content[d.item].querySelectorAll(":scope > *")
http://prntscr.com/5wsinf
modal  window is not appear

any ideas?

**Comment by dixso** [comment]
Hi,
Try this new release:
https://github.com/dixso/custombox/releases/tag/2.2.4
Regards.

**Comment by tsok** [comment]
Yes, it works! Thank you for the quick response!
