### ISSUE TITLE
Automatically run on page load without clicking any button

### ISSUE THREAD

**Issue by raid01alpha** [dixso/custombox#96]
Hi, I would like to use this to run on page load like an alert or a confirmation box instead of clicking on a button, how can I do that?  Sorry I am not good in javascript or jquery either.  Thanks in advance!

**Comment by dixso** [comment]
Hi,
For example:
<pre>
$(function () {
    Custombox.open({
        target:     '#modal'
    });
    e.preventDefault();
});
</pre>

**Comment by digitalgenossen** [comment]
Hi,

I have got 3 modals on my page and want #modal3 to open automatically on page load.
Can you tell me how to do that?

Here is my code:

![unbenannt-4](https://cloud.githubusercontent.com/assets/6715837/10726214/a1776642-7bd1-11e5-8e60-c48f96a4d108.jpg)


Thank you :-)
Kai

**Comment by dixso** [comment]
Hi,
You have the answer more top.
