### ISSUE TITLE
Jquery Tooltip Z-index behind Modal

### ISSUE THREAD

**Issue by mediadr** [dixso/custombox#97]
Using the custombox modal, and I have a button inside the modal that when rolled over displays the Jquery tooltip. Problem is the tooltip is showing up behind the modal. No matter what I set the z-index of the tooltip class to, custombox just makes its z-index larger. How can this be fixed? thanks.

**Comment by dixso** [comment]
Hi,
Add the option zIndex (default is auto).
For example:
<pre>
    $('.example').on('click', function ( e ) {
        Custombox.open({
            target:     '#example',
            zIndex:     11
        });
        e.preventDefault();
    });
</pre>

**Comment by mediadr** [comment]
tried that too, still was behind it. Looks like jquery is inserting the div for the tooltip, just before the closing body tag. Even when I set the zindex of the modal to 1, its z-index properties are in the 10,000+ range.

**Comment by dixso** [comment]
I'm sorry but I don't understand what you say.
¿Would you write your code in jsfiddle.net?
