### ISSUE TITLE
Bug with Custom Box & Tiny MCE

### ISSUE THREAD

**Issue by mediadr** [dixso/custombox#99]
Tally this one up with the several bugs I've seen that all involve the reloading of elements upon launch of the modal.

So we use TInyMCE for our WYSIWYG to replace textarea, and when it contains text, and the user hits submit, which uses Custom Box for a preloader (while the data is handled by AJAX behind the scene) the Tiny MCE text box keeps showing up empty. It specificlly becomes empty once the modal pops.

Why is it nessecary to "reload" content on the webpage to pop this modal? While you may not be able to tell with a refresh of images, because they show the same thing, its cretaing problems with things more complex like Flash elements and Jquery Libraries like Tiny MCE?

**Comment by dixso** [comment]
When load AJAX with any library, are not loading the script inside.
Need the callback "complete" to execute any script.
¿Would you write your code in jsfiddle.net?

**Comment by DruidKuma** [comment]
Have the similar issue. I'm using your library in an angular application and on the page where I've inited TinyMCE editor, I click on the toggle modal button. It works as expected, but tinymce become immediately broken and doesn't work any more.
I've found out that this behaviour cause these code:
```
switch ( item ) {
                case 'container':
                    this.main = document.createElement('div');
            
                    // If we comment out these lines, nothing is broken, but animation does not influence the page (e.g. for 'push' animation)
                    while ( document.body.firstChild ) {
                        this.main.appendChild(document.body.firstChild);
                    }

                    document.body.appendChild(this.main);
                    break;
```
